---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        args: [--tab-width, "2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
